import 'dart:io';

import 'package:lattice_core/lattice_core.dart';
import 'package:path/path.dart' as p;

import 'app_icon.dart';

/// Writes the per-format configuration `flutter_distributor` insists on
/// (§7.9 step 4).
///
/// Each packaging target reads its own
/// `[platform]/packaging/[target]/make_config.yaml`, and refuses to run
/// without one. Generating them is the
/// difference between "run this one command" and "first go read the
/// flutter_distributor docs" — which is the whole of §7.9's promise that a
/// user never has to meet a platform's packaging toolchain.
class PackagingConfig {
  const PackagingConfig();

  /// Icon path relative to the generated project root.
  static const iconPath = 'packaging/icon.png';

  /// Writes configuration for every format [targets] can produce.
  ///
  /// Returns the files it created; existing ones are left alone, so hand
  /// edits survive a regeneration.
  Future<List<String>> write(
    String outputDir,
    ProjectConfig config,
    List<BuildTarget> targets,
  ) async {
    final written = <String>[];

    if (await const AppIcon().writePlaceholder(p.join(outputDir, iconPath))) {
      written.add(iconPath);
    }

    for (final target in targets) {
      for (final entry in _configsFor(target, config).entries) {
        final relative = p.join(
          _platformDirectory(target),
          'packaging',
          entry.key,
          'make_config.yaml',
        );
        final file = File(p.join(outputDir, relative));
        if (file.existsSync()) continue;
        await file.parent.create(recursive: true);
        await file.writeAsString(entry.value);
        written.add(relative);
      }
    }
    return written;
  }

  static String _platformDirectory(BuildTarget target) => switch (target) {
        BuildTarget.linux => 'linux',
        BuildTarget.windows => 'windows',
        BuildTarget.macos => 'macos',
        BuildTarget.android => 'android',
        BuildTarget.ios => 'ios',
        BuildTarget.web => 'web',
      };

  Map<String, String> _configsFor(BuildTarget target, ProjectConfig config) {
    // Resolved against the working directory — which is the project root,
    // where flutter_distributor runs — not against this config file. The
    // maker does a plain `File(makeConfig.icon)`.
    const icon = iconPath;
    final identifier = config.packageName.replaceAll('_', '-');

    return switch (target) {
      BuildTarget.linux => {
          'appimage': '''
$_header
display_name: ${_yaml(config.appName)}
icon: $icon
generic_name: ${_yaml(config.appName)}
categories:
  - Utility
keywords:
  - ${config.appName}
startup_notify: true
''',
          'deb': '''
$_header
display_name: ${_yaml(config.appName)}
package_name: ${_yaml(identifier)}
maintainer:
  name: ${_yaml(config.organization)}
  email: ${_yaml('noreply@${_domainOf(config.bundleId)}')}
icon: $icon
generic_name: ${_yaml(config.appName)}
priority: optional
section: utils
essential: false
installed_size: 0
categories:
  - Utility
keywords:
  - ${config.appName}
''',
        },
      BuildTarget.windows => {
          'exe': '''
$_header
# Inno Setup installer. Untested by the project's own CI.
app_id: ${_yaml(config.bundleId)}
publisher: ${_yaml(config.organization)}
display_name: ${_yaml(config.appName)}
create_desktop_icon: true
install_dir_name: ${_yaml(config.appName)}
''',
          'msix': '''
$_header
# Untested by the project's own CI.
display_name: ${_yaml(config.appName)}
identity_name: ${_yaml(config.bundleId)}
publisher_display_name: ${_yaml(config.organization)}
''',
        },
      BuildTarget.macos => {
          'dmg': '''
$_header
# Unsigned. See docs/signing.md before sending this to anyone.
# Untested by the project's own CI.
title: ${_yaml(config.appName)}
icon: $icon
contents:
  - x: 448
    y: 344
    type: link
    path: /Applications
  - x: 192
    y: 344
    type: file
    path: ${_yaml('build/macos/Build/Products/Release/${config.appName}.app')}
''',
        },
      _ => const {},
    };
  }

  static String _domainOf(String bundleId) {
    final parts = bundleId.split('.');
    return parts.length >= 2 ? '${parts[1]}.${parts[0]}' : 'example.com';
  }

  static String _yaml(String value) => "'${value.replaceAll("'", "''")}'";

  static const _header = '''
# Generated by Lattice. Edit freely — regeneration never overwrites this file.''';
}
