import 'package:code_builder/code_builder.dart';
import 'package:lattice_core/lattice_core.dart';

import '../naming.dart';
import 'render.dart';

/// Emits `lib/main.dart`: the `MaterialApp` and the route table.
class AppEmitter {
  const AppEmitter();

  String emit(Project project) {
    final config = project.config;
    final appClass = '${Naming.pascal(config.appName)}App';
    final home = project.homePage;

    // A page with parameters cannot be a `const` tear-off: its builder has to
    // unpack `settings.arguments` first (R12).
    final routes = {
      for (final page in project.pages) page.route: _routeBuilder(page),
    };

    final library = Library(
      (b) => b
        ..directives.addAll([
          Directive.import('package:flutter/material.dart'),
          if (project.collections.isNotEmpty)
            Directive.import('collections.dart'),
          for (final page in project.pages)
            Directive.import('pages/${page.fileName}'),
        ])
        ..body.addAll([
          Method(
            (m) => m
              ..name = 'main'
              // Storage is asynchronous, so the stored data has to be in hand
              // before the first frame — otherwise the app renders empty and
              // then jumps, which reads as data loss.
              ..returns = refer(
                project.collections.isEmpty ? 'void' : 'Future<void>',
              )
              ..modifier =
                  project.collections.isEmpty ? null : MethodModifier.async
              ..body = Code(
                project.collections.isEmpty
                    ? 'runApp(const $appClass());'
                    : 'WidgetsFlutterBinding.ensureInitialized();\n'
                        'await loadCollections();\n'
                        'runApp(const $appClass());',
              ),
          ),
          Class(
            (b) => b
              ..name = appClass
              ..extend = refer('StatelessWidget')
              ..constructors.add(
                Constructor(
                  (c) => c
                    ..constant = true
                    ..optionalParameters.add(
                      Parameter(
                        (p) => p
                          ..name = 'key'
                          ..named = true
                          ..toSuper = true,
                      ),
                    ),
                ),
              )
              ..methods.add(
                Method(
                  (m) => m
                    ..name = 'build'
                    ..returns = refer('Widget')
                    ..annotations.add(refer('override'))
                    ..requiredParameters.add(
                      Parameter(
                        (p) => p
                          ..name = 'context'
                          ..type = refer('BuildContext'),
                      ),
                    )
                    ..body = Code('''
return MaterialApp(
  title: '${_escape(config.appName)}',
  debugShowCheckedModeBanner: false,
  theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.indigo),
  initialRoute: '${_escape(home?.route ?? '/')}',
  routes: {
${routes.entries.map((e) => "    '${_escape(e.key)}': ${e.value},").join('\n')}
  },
);'''),
                ),
              ),
          ),
        ]),
    );

    return '$_header\n${library.accept(newEmitter())}';
  }

  String _routeBuilder(Page page) {
    if (page.parameters.isEmpty) {
      return '(context) => const ${page.className}()';
    }
    final reads = page.parameters.map(_readArgument).join(', ');
    return '''(context) {
      final arguments =
          ModalRoute.of(context)!.settings.arguments as Map<String, Object?>? ??
          const {};
      return ${page.className}($reads);
    }''';
  }

  /// One constructor argument, read out of the navigation arguments.
  String _readArgument(FieldDef parameter) {
    final access = "arguments['${parameter.name}']";
    final type = parameter.type;
    if (parameter.defaultValue != null) {
      final fallback = _defaultLiteral(parameter);
      return '${parameter.name}: $access == null ? $fallback '
          ': $access as ${_nonNull(type).dartName}';
    }
    if (type is NullableType) {
      return '${parameter.name}: $access as ${type.dartName}';
    }
    return '${parameter.name}: $access! as ${type.dartName}';
  }

  static LatticeType _nonNull(LatticeType type) =>
      type is NullableType ? type.inner : type;

  static String _defaultLiteral(FieldDef parameter) {
    final value = parameter.defaultValue;
    return switch (value) {
      final String s => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'",
      final bool b => '$b',
      final num n => '$n',
      _ => 'null',
    };
  }

  static const _header = '''
// Generated by Lattice.
//
// The route table mirrors the project's pages; add a page in the editor and it
// appears here.
''';

  static String _escape(String value) => value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$');
}
