import 'package:code_builder/code_builder.dart';
import 'package:lattice_core/lattice_core.dart';

import '../naming.dart';
import 'render.dart';

/// Emits `lib/main.dart`: the `MaterialApp` and the route table.
class AppEmitter {
  const AppEmitter();

  String emit(Project project) {
    final config = project.config;
    final appClass = '${Naming.pascal(config.appName)}App';
    final home = project.homePage;

    final routes = {
      for (final page in project.pages) page.route: 'const ${page.className}()',
    };

    final library = Library(
      (b) => b
        ..directives.addAll([
          Directive.import('package:flutter/material.dart'),
          for (final page in project.pages)
            Directive.import('pages/${page.fileName}'),
        ])
        ..body.addAll([
          Method(
            (m) => m
              ..name = 'main'
              ..returns = refer('void')
              ..body = Code('runApp(const $appClass());'),
          ),
          Class(
            (b) => b
              ..name = appClass
              ..extend = refer('StatelessWidget')
              ..constructors.add(
                Constructor(
                  (c) => c
                    ..constant = true
                    ..optionalParameters.add(
                      Parameter(
                        (p) => p
                          ..name = 'key'
                          ..named = true
                          ..toSuper = true,
                      ),
                    ),
                ),
              )
              ..methods.add(
                Method(
                  (m) => m
                    ..name = 'build'
                    ..returns = refer('Widget')
                    ..annotations.add(refer('override'))
                    ..requiredParameters.add(
                      Parameter(
                        (p) => p
                          ..name = 'context'
                          ..type = refer('BuildContext'),
                      ),
                    )
                    ..body = Code('''
return MaterialApp(
  title: '${_escape(config.appName)}',
  debugShowCheckedModeBanner: false,
  theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.indigo),
  initialRoute: '${_escape(home?.route ?? '/')}',
  routes: {
${routes.entries.map((e) => "    '${_escape(e.key)}': (context) => ${e.value},").join('\n')}
  },
);'''),
                ),
              ),
          ),
        ]),
    );

    return '$_header\n${library.accept(newEmitter())}';
  }

  static const _header = '''
// Generated by Lattice.
//
// The route table mirrors the project's pages; add a page in the editor and it
// appears here.
''';

  static String _escape(String value) => value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$');
}
