import 'package:lattice_core/lattice_core.dart';

/// Generates the data layer (R19).
///
/// Three files rather than one, because the storage half has to differ by
/// platform and a conditional import is the only way to say that in Dart
/// without dragging in a package.
class CollectionEmitter {
  const CollectionEmitter();

  static const _header = '''
// Generated by Lattice.
//
// A collection is a List<T> that survives a restart, kept in a signal so a
// page rebuilds when it changes. Serialization is the model's own — the same
// codec the server boundary uses (§7.7).
''';

  /// `lib/collections.dart` — the collections this project declares.
  String collections(Project project, ProjectConfig config) {
    final reactive = config.runtime == RuntimeBackend.signals
        ? "import 'package:signals_flutter/signals_flutter.dart';"
        : "import 'package:lattice_runtime/lattice_runtime.dart';";

    final buffer = StringBuffer()
      ..writeln(_header)
      ..writeln("import 'dart:convert';")
      ..writeln()
      ..writeln(reactive)
      ..writeln()
      ..writeln("import 'models.dart';")
      ..writeln("import 'store.dart';")
      ..writeln()
      ..writeln('''
/// One typed list, persisted under [key].
class LatticeCollection<T> {
  LatticeCollection({
    required this.key,
    required this.decode,
    required this.encode,
    required this.persist,
  });

  final String key;
  final T Function(Map<String, Object?> json) decode;
  final Map<String, Object?> Function(T value) encode;
  final bool persist;

  final items = signal<List<T>>(const []);

  /// Reads whatever was stored last. Called once at startup; a store that
  /// holds nothing, or something unreadable, leaves the list empty rather
  /// than failing to launch.
  Future<void> load() async {
    if (!persist) return;
    final raw = await LatticeStore.read(key);
    if (raw == null) return;
    try {
      final decoded = jsonDecode(raw);
      if (decoded is! List) return;
      items.value = [
        for (final entry in decoded)
          if (entry is Map<String, Object?>) decode(entry),
      ];
    } on Object {
      // Stored data from an older shape of the model. Losing it is bad;
      // refusing to start is worse.
      items.value = const [];
    }
  }

  Future<void> _save() async {
    if (!persist) return;
    await LatticeStore.write(
      key,
      jsonEncode([for (final item in items.value) encode(item)]),
    );
  }

  Future<void> add(T item) async {
    items.value = [...items.value, item];
    await _save();
  }

  Future<void> replaceAt(int index, T item) async {
    if (index < 0 || index >= items.value.length) return;
    final next = List<T>.of(items.value);
    next[index] = item;
    items.value = next;
    await _save();
  }

  Future<void> removeAt(int index) async {
    if (index < 0 || index >= items.value.length) return;
    final next = List<T>.of(items.value)..removeAt(index);
    items.value = next;
    await _save();
  }

  Future<void> clear() async {
    items.value = const [];
    await _save();
  }
}''');

    for (final collection in project.collections) {
      final element = collection.element;
      buffer
        ..writeln()
        ..writeln('final ${collection.name} = LatticeCollection<$element>(')
        ..writeln("  key: '${collection.name}',")
        ..writeln('  decode: $element.fromJson,')
        ..writeln('  encode: (value) => value.toJson(),')
        ..writeln('  persist: ${collection.persist},')
        ..writeln(');');
    }

    buffer
      ..writeln()
      ..writeln('/// Called once before the app runs, so the first frame '
          'already has the stored data.')
      ..writeln('Future<void> loadCollections() async {')
      ..writeln('  await Future.wait([');
    for (final collection in project.collections) {
      buffer.writeln('    ${collection.name}.load(),');
    }
    buffer
      ..writeln('  ]);')
      ..writeln('}');

    return buffer.toString();
  }

  /// `lib/store.dart` — the platform-independent face of storage.
  String store() => '''$_header
import 'store_io.dart' if (dart.library.js_interop) 'store_web.dart'
    as platform;

/// Key-value storage, whichever kind this platform has.
class LatticeStore {
  const LatticeStore._();

  static Future<String?> read(String key) => platform.read(key);

  static Future<void> write(String key, String value) =>
      platform.write(key, value);
}
''';

  /// `lib/store_io.dart` — a JSON file next to the executable's data.
  String storeIo(ProjectConfig config) => '''$_header
import 'dart:io';

Future<File> _file(String key) async {
  final home = Platform.environment['HOME'] ??
      Platform.environment['USERPROFILE'] ??
      Directory.systemTemp.path;
  final directory = Directory('\$home/.local/share/${config.packageName}');
  await directory.create(recursive: true);
  return File('\${directory.path}/\$key.json');
}

Future<String?> read(String key) async {
  final file = await _file(key);
  if (!file.existsSync()) return null;
  return file.readAsString();
}

Future<void> write(String key, String value) async {
  final file = await _file(key);
  await file.writeAsString(value);
}
''';

  /// `lib/store_web.dart` — the same shape, backed by localStorage.
  String storeWeb(ProjectConfig config) => '''$_header
import 'package:web/web.dart' as web;

String _key(String key) => '${config.packageName}.\$key';

Future<String?> read(String key) async =>
    web.window.localStorage.getItem(_key(key));

Future<void> write(String key, String value) async =>
    web.window.localStorage.setItem(_key(key), value);
''';
}
