import 'package:code_builder/code_builder.dart';
import 'package:lattice_core/lattice_core.dart';

import 'render.dart';

/// Emits `lib/models.dart`: one immutable class per user struct, with
/// `copyWith` and hand-rolled JSON codecs.
///
/// Hand-rolled rather than `json_serializable` because Lattice already *is* a
/// code generator — pulling in build_runner would mean a second one (§9).
class ModelEmitter {
  const ModelEmitter();

  String emit(List<DataModelDef> models) {
    // Deep comparison is done by two helpers emitted into this file rather
    // than imported, so the models file has no dependencies at all and can be
    // shared verbatim with a generated server, which has no Flutter (§7.7).
    // Emitted only where used: an unused private function is a diagnostic in
    // the generated project, and G2 asks for none.
    final needsList = models.any(
      (m) => m.fields.any((f) => _isKind(f.type, list: true)),
    );
    final needsMap = models.any(
      (m) => m.fields.any((f) => _isKind(f.type, list: false)),
    );
    final library = Library(
      (b) => b
        // No imports at all: models are shared verbatim between the client
        // and a generated server (§7.7), and the server has no Flutter. The
        // two comparison helpers below are cheaper than a dependency.
        ..body.addAll([
          for (final model in models) _class(model),
          if (needsList) _listEqualsHelper(),
          if (needsMap) _mapEqualsHelper(),
        ]),
    );
    return '$_header\n${library.accept(newEmitter())}';
  }

  Spec _listEqualsHelper() => Method(
        (m) => m
          ..name = '_listEquals'
          ..returns = refer('bool')
          ..types.add(refer('T'))
          ..requiredParameters.addAll([
            Parameter((p) => p
              ..name = 'a'
              ..type = refer('List<T>?')),
            Parameter((p) => p
              ..name = 'b'
              ..type = refer('List<T>?')),
          ])
          ..body = const Code('''
if (identical(a, b)) return true;
if (a == null || b == null || a.length != b.length) return false;
for (var i = 0; i < a.length; i++) {
  if (a[i] != b[i]) return false;
}
return true;'''),
      );

  Spec _mapEqualsHelper() => Method(
        (m) => m
          ..name = '_mapEquals'
          ..returns = refer('bool')
          ..types.addAll([refer('K'), refer('V')])
          ..requiredParameters.addAll([
            Parameter((p) => p
              ..name = 'a'
              ..type = refer('Map<K, V>?')),
            Parameter((p) => p
              ..name = 'b'
              ..type = refer('Map<K, V>?')),
          ])
          ..body = const Code('''
if (identical(a, b)) return true;
if (a == null || b == null || a.length != b.length) return false;
for (final entry in a.entries) {
  if (!b.containsKey(entry.key) || b[entry.key] != entry.value) return false;
}
return true;'''),
      );

  /// Whether [type] needs element-wise comparison, and of which kind.
  static bool _isKind(LatticeType type, {required bool list}) => switch (type) {
        ListType() => list,
        MapType() => !list,
        NullableType(:final inner) => _isKind(inner, list: list),
        _ => false,
      };

  static const _header = '''
// Generated by Lattice from models/.
//
// Plain immutable data classes — no annotations, no build_runner, nothing to
// re-run after ejecting.
''';

  Class _class(DataModelDef model) => Class(
        (b) => b
          ..name = model.name
          ..modifier = ClassModifier.final$
          ..constructors.addAll([
            Constructor(
              (c) => c
                ..constant = true
                ..optionalParameters.addAll([
                  for (final field in model.fields)
                    Parameter(
                      (p) => p
                        ..name = field.name
                        ..named = true
                        ..toThis = true
                        ..required = _isRequired(field)
                        ..defaultTo = _defaultFor(field),
                    ),
                ]),
            ),
            Constructor(
              (c) => c
                ..factory = true
                ..name = 'fromJson'
                ..requiredParameters.add(
                  Parameter(
                    (p) => p
                      ..name = 'json'
                      ..type = refer('Map<String, Object?>'),
                  ),
                )
                ..lambda = true
                ..body = Code(
                  '${model.name}('
                  '${model.fields.map((f) => '${f.name}: ${_fromJson(f)}').join(', ')}'
                  ')',
                ),
            ),
          ])
          ..fields.addAll([
            for (final field in model.fields)
              Field(
                (f) => f
                  ..name = field.name
                  ..modifier = FieldModifier.final$
                  ..type = refer(field.type.dartName),
              ),
          ])
          ..methods.addAll([
            _toJson(model),
            _copyWith(model),
            _equals(model),
            _hashCode(model),
            _toString(model),
          ]),
      );

  bool _isRequired(FieldDef field) =>
      field.defaultValue == null && field.type is! NullableType;

  Code? _defaultFor(FieldDef field) {
    if (field.defaultValue == null) return null;
    final emitted = const LiteralEmitterShim().literal(field);
    return emitted == null ? null : Code(emitted);
  }

  Method _toJson(DataModelDef model) => Method(
        (m) => m
          ..name = 'toJson'
          ..returns = refer('Map<String, Object?>')
          ..lambda = true
          ..body = Code(
            '{${model.fields.map((f) => "'${f.jsonKey}': ${_toJsonValue(f.type, f.name)}").join(', ')}}',
          ),
      );

  Method _copyWith(DataModelDef model) => Method(
        (m) => m
          ..name = 'copyWith'
          ..returns = refer(model.name)
          ..optionalParameters.addAll([
            for (final field in model.fields)
              Parameter(
                (p) => p
                  ..name = field.name
                  ..named = true
                  ..type = refer(_nullable(field.type)),
              ),
          ])
          ..lambda = true
          ..body = Code(
            '${model.name}('
            '${model.fields.map((f) => '${f.name}: ${f.name} ?? this.${f.name}').join(', ')}'
            ')',
          ),
      );

  Method _equals(DataModelDef model) => Method(
        (m) => m
          ..name = 'operator =='
          ..returns = refer('bool')
          ..annotations.add(refer('override'))
          ..requiredParameters.add(
            Parameter(
              (p) => p
                ..name = 'other'
                ..type = refer('Object'),
            ),
          )
          ..lambda = true
          ..body = Code(
            'other is ${model.name}'
            '${model.fields.map((f) => ' && ${_compare(f)}').join()}',
          ),
      );

  Method _hashCode(DataModelDef model) => Method(
        (m) => m
          ..name = 'hashCode'
          ..type = MethodType.getter
          ..returns = refer('int')
          ..annotations.add(refer('override'))
          ..lambda = true
          ..body = Code(
            model.fields.isEmpty
                ? '${model.name}.hashCode'
                : model.fields.length == 1
                    ? '${_hashOf(model.fields.single)}.hashCode'
                    : 'Object.hash('
                        '${model.fields.map(_hashOf).join(', ')})',
          ),
      );

  Method _toString(DataModelDef model) => Method(
        (m) => m
          ..name = 'toString'
          ..returns = refer('String')
          ..annotations.add(refer('override'))
          ..lambda = true
          ..body = Code(
            "'${model.name}("
            "${model.fields.map((f) => '${f.name}: \$${f.name}').join(', ')}"
            ")'",
          ),
      );

  /// Field comparison for `==`. Collections compare element-wise, so two
  /// values built the same way are equal — anything else would surprise a user
  /// whose Signal holds a rebuilt list.
  static String _compare(FieldDef field) {
    final name = field.name;
    return switch (field.type) {
      ListType() => '_listEquals(other.$name, $name)',
      MapType() => '_mapEquals(other.$name, $name)',
      NullableType(inner: ListType()) => '_listEquals(other.$name, $name)',
      NullableType(inner: MapType()) => '_mapEquals(other.$name, $name)',
      _ => 'other.$name == $name',
    };
  }

  /// Hash contribution for a field, kept consistent with [_compare].
  static String _hashOf(FieldDef field) {
    final name = field.name;
    return switch (field.type) {
      ListType() => 'Object.hashAll($name)',
      NullableType(inner: ListType()) =>
        '$name == null ? null : Object.hashAll($name!)',
      MapType() => '$name.length',
      NullableType(inner: MapType()) => '$name?.length',
      _ => name,
    };
  }

  static String _nullable(LatticeType type) =>
      type is NullableType ? type.dartName : '${type.dartName}?';

  /// Reads one field out of decoded JSON.
  String _fromJson(FieldDef field) {
    final access = "json['${field.jsonKey}']";
    final type = field.type;
    if (type is NullableType) {
      return '$access == null ? null : ${_decode(type.inner, access)}';
    }
    if (field.defaultValue != null) {
      return '$access == null ? ${_defaultLiteral(field)} : ${_decode(type, access)}';
    }
    return _decode(type, access);
  }

  String _defaultLiteral(FieldDef field) =>
      const LiteralEmitterShim().literal(field) ?? 'null';

  String _decode(LatticeType type, String access) => switch (type) {
        ModelType(:final name) =>
          '$name.fromJson($access as Map<String, Object?>)',
        ListType(:final element) =>
          '[for (final e in $access as List<Object?>) '
              '${_decode(element, 'e')}]',
        MapType(:final value) =>
          '{for (final e in ($access as Map<String, Object?>).entries) '
              'e.key: ${_decode(value, 'e.value')}}',
        NullableType(:final inner) =>
          '$access == null ? null : ${_decode(inner, access)}',
        PrimitiveType(kind: PrimitiveKind.double$) =>
          '($access as num).toDouble()',
        _ => '$access as ${type.dartName}',
      };

  String _toJsonValue(LatticeType type, String access) => switch (type) {
        ModelType() => '$access.toJson()',
        NullableType(inner: ModelType()) => '$access?.toJson()',
        ListType(:final element)
            when element is ModelType ||
                element is ListType ||
                element is MapType =>
          '[for (final e in $access) ${_toJsonValue(element, 'e')}]',
        MapType(:final value)
            when value is ModelType || value is ListType || value is MapType =>
          '{for (final e in $access.entries) e.key: ${_toJsonValue(value, 'e.value')}}',
        NullableType(:final inner) => switch (inner) {
            ModelType() ||
            ListType() ||
            MapType() =>
              '$access == null ? null : ${_toJsonValue(inner, '$access!')}',
            _ => access,
          },
        _ => access,
      };
}

/// Renders a field's JSON default as Dart source. Split out so the model
/// emitter does not depend on the widget-oriented literal machinery.
class LiteralEmitterShim {
  const LiteralEmitterShim();

  String? literal(FieldDef field) {
    final value = field.defaultValue;
    return switch (value) {
      null => null,
      final String s => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'",
      final bool b => '$b',
      final num n => '$n',
      final List<Object?> l when l.isEmpty => 'const []',
      final Map<Object?, Object?> m when m.isEmpty => 'const {}',
      _ => null,
    };
  }
}
