import 'package:code_builder/code_builder.dart';
import 'package:lattice_core/lattice_core.dart';

import '../ir/page_ir.dart';
import 'literals.dart';
import 'render.dart';

/// Step 3 of the pipeline (§7.5): one [PageIr] becomes one Dart library.
///
/// The shape is fixed on purpose — signals as fields, one method per event
/// chain, a plain `build` — because that is what a Flutter developer would
/// have written by hand, and because those anchors are what a future
/// graph ↔ code round trip would key off (R18).
/// `dart:` and `package:` imports pass through; everything else is a path
/// relative to `lib/`, and pages live one directory below it.
String _resolveImport(String import) =>
    import.contains(':') ? import : '../$import';

class PageEmitter {
  const PageEmitter();

  static const _material = 'package:flutter/material.dart';

  String emit(ProjectIr projectIr, PageIr ir) {
    final config = projectIr.project.config;
    final literals = LiteralEmitter(models: projectIr.project.models);
    final needsRuntime = ir.signals.isNotEmpty || ir.hoisted.isNotEmpty;

    final library = Library(
      (b) => b
        ..directives.addAll([
          if (ir.usesJson) Directive.import('dart:convert'),
          Directive.import(_material),
          if (ir.usesHttp)
            Directive.import('package:http/http.dart', as: 'http'),
          if (needsRuntime) Directive.import(_runtimeImport(config)),
          if (ir.usesModels) Directive.import('../models.dart'),
          if (ir.usesRpc) Directive.import('../rpc.dart'),
          for (final prefab in ir.usedPrefabs)
            Directive.import('../prefabs/$prefab'),
          // Hand-written helpers the graph calls into (§7.8). Pages live one
          // level down from lib/, so a project-relative path gets `../`.
          // A URI that names its own scheme — `dart:math`, `package:…` — is
          // already absolute and must be left alone.
          for (final import in ir.extraImports)
            Directive.import(_resolveImport(import)),
        ])
        ..body.addAll([
          if (ir.isStateful)
            ..._stateful(ir, literals)
          else
            _stateless(ir, literals),
          ..._helpers(ir),
        ]),
    );

    return '${_header(ir)}\n${library.accept(newEmitter())}';
  }

  String _runtimeImport(ProjectConfig config) => switch (config.runtime) {
        RuntimeBackend.signals =>
          'package:signals_flutter/signals_flutter.dart',
        RuntimeBackend.valueNotifier =>
          'package:lattice_runtime/lattice_runtime.dart',
      };

  String _header(PageIr ir) => '''
// Generated by Lattice from ${ir.unit.id}.
//
// Safe to edit once you have ejected: this is ordinary Flutter code with no
// runtime dependency on the editor. Node ids appear as comments so a change
// here can still be traced back to the graph.
''';

  // ---------------------------------------------------------------------------

  List<Spec> _stateful(PageIr ir, LiteralEmitter literals) {
    final stateName = '_${ir.className}State';
    return [
      Class(
        (b) => b
          ..name = ir.className
          ..extend = refer('StatefulWidget')
          ..constructors.add(_pageConstructor(ir, literals))
          ..fields.addAll(_parameterFields(ir))
          ..methods.add(
            Method(
              (m) => m
                ..name = 'createState'
                ..returns = refer('State<${ir.className}>')
                ..annotations.add(refer('override'))
                ..lambda = true
                ..body = Code('$stateName()'),
            ),
          ),
      ),
      Class(
        (b) => b
          ..name = stateName
          ..extend = refer('State<${ir.className}>')
          ..fields.addAll([
            for (final signal in ir.signals) _signalField(signal),
            for (final hoist in ir.hoisted) _hoistField(hoist),
            for (final controller in ir.controllers) ...[
              _controllerField(controller),
              if (controller.isReactive) _disposerField(controller),
            ],
          ])
          ..methods.addAll([
            if (ir.needsLifecycle) ...[
              _initState(ir),
              _dispose(ir),
            ],
            for (final handler in ir.handlers) _handlerMethod(handler),
            _buildMethod(ir),
          ]),
      ),
    ];
  }

  Spec _stateless(PageIr ir, LiteralEmitter literals) => Class(
        (b) => b
          ..name = ir.className
          ..extend = refer('StatelessWidget')
          ..constructors.add(_pageConstructor(ir, literals))
          ..fields.addAll(_parameterFields(ir))
          ..methods.add(_buildMethod(ir)),
      );

  /// `const HomePage({super.key})`, plus one named parameter per value the
  /// page must be navigated to with.
  Constructor _pageConstructor(PageIr ir, LiteralEmitter literals) =>
      Constructor(
        (c) => c
          ..constant = true
          ..optionalParameters.addAll([
            Parameter(
              (p) => p
                ..name = 'key'
                ..named = true
                ..toSuper = true,
            ),
            for (final parameter in ir.parameters)
              Parameter(
                (p) => p
                  ..name = parameter.name
                  ..named = true
                  ..toThis = true
                  // A callback the host may or may not care about: a prefab
                  // that fires `onTap` into nothing is a normal prefab, so
                  // these are optional and the field is nullable.
                  ..required = parameter.type is! EventType &&
                      parameter.defaultValue == null &&
                      parameter.type is! NullableType
                  // A non-nullable optional parameter is only legal with a
                  // default, so the declared default is emitted here too.
                  ..defaultTo = parameter.defaultValue == null
                      ? null
                      : literals
                          .emit(parameter.type, parameter.defaultValue)
                          .standalone()
                          .code,
              ),
          ]),
      );

  List<Field> _parameterFields(PageIr ir) => [
        for (final parameter in ir.parameters)
          Field(
            (f) => f
              ..name = parameter.name
              ..modifier = FieldModifier.final$
              // Nullable, matching the optional constructor parameter: the
              // call site is `onTap?.call()`.
              ..type = refer(
                parameter.type is EventType
                    ? '${parameter.type.dartName}?'
                    : parameter.type.dartName,
              ),
          ),
      ];

  Field _signalField(SignalIr signal) => Field(
        (f) => f
          ..name = signal.name
          ..modifier = FieldModifier.final$
          ..docs.add('// ${signal.nodeId}')
          ..assignment = Code(
            'signal<${signal.type.dartName}>'
            '(${renderExpression(signal.init.standalone())})',
          ),
      );

  Field _hoistField(HoistedIr hoist) => Field(
        (f) => f
          ..name = hoist.name
          ..late = true
          ..modifier = FieldModifier.final$
          ..docs.add('// ${hoist.pin.nodeId}')
          ..assignment = Code(
            'computed(() => ${renderExpression(hoist.body.bare())})',
          ),
      );

  /// Declared `late` and assigned in `initState`, because the seed value may
  /// read a signal and fields are initialised before `initState` runs.
  Field _controllerField(ControllerIr controller) => Field(
        (f) => f
          ..name = controller.name
          ..late = true
          ..modifier = FieldModifier.final$
          ..type = refer(controller.type)
          ..docs.add('// ${controller.widgetId}'),
      );

  Field _disposerField(ControllerIr controller) => Field(
        (f) => f
          ..name = controller.disposerName
          ..late = true
          ..modifier = FieldModifier.final$
          ..type = refer('void Function()'),
      );

  Method _initState(PageIr ir) => Method(
        (m) => m
          ..name = 'initState'
          ..returns = refer('void')
          ..annotations.add(refer('override'))
          ..body = Block.of([
            const Code('super.initState();'),
            for (final controller in ir.controllers) ...[
              Code(
                '${controller.name} = ${controller.type}('
                '${controller.property}: '
                '${renderExpression(controller.initial.bare())});',
              ),
              if (controller.isReactive)
                // The guard is what keeps typing from fighting the signal: an
                // unconditional write would reset the cursor on every rebuild.
                Code('''
${controller.disposerName} = effect(() {
  final next = ${renderExpression(controller.initial.bare())};
  if (${controller.name}.${controller.property} != next) {
    ${controller.name}.${controller.property} = next;
  }
});'''),
            ],
          ]),
      );

  Method _dispose(PageIr ir) => Method(
        (m) => m
          ..name = 'dispose'
          ..returns = refer('void')
          ..annotations.add(refer('override'))
          ..body = Block.of([
            for (final controller in ir.controllers) ...[
              if (controller.isReactive) Code('${controller.disposerName}();'),
              Code('${controller.name}.dispose();'),
            ],
            const Code('super.dispose();'),
          ]),
      );

  Method _handlerMethod(HandlerIr handler) => Method(
        (m) => m
          ..name = handler.name
          ..returns = refer(handler.isAsync ? 'Future<void>' : 'void')
          ..modifier = handler.isAsync ? MethodModifier.async : null
          ..docs.add('// ${handler.trace.join(' -> ')}')
          ..requiredParameters.addAll([
            if (handler.payloadType != null)
              Parameter(
                (p) => p
                  ..name = handler.payloadName
                  ..type = refer(handler.payloadType!.dartName),
              ),
            for (final parameter in handler.scopeParameters)
              Parameter(
                (p) => p
                  ..name = parameter.name
                  ..type = refer(parameter.type.dartName),
              ),
          ])
          ..body = Block.of(handler.statements),
      );

  Method _buildMethod(PageIr ir) => Method(
        (m) => m
          ..name = 'build'
          ..returns = refer('Widget')
          ..annotations.add(refer('override'))
          ..requiredParameters.add(
            Parameter(
              (p) => p
                ..name = 'context'
                ..type = refer('BuildContext'),
            ),
          )
          ..body = Code('return ${renderExpression(ir.body.standalone())};'),
      );

  /// `Computed` and `Dart Code` bodies become top-level private functions:
  /// they are pure by construction, so nothing is gained by hiding them in the
  /// State class, and a reader can see at a glance that they touch no state.
  List<Spec> _helpers(PageIr ir) => [
        for (final helper in ir.helpers)
          Method(
            (m) => m
              ..name = helper.name
              ..returns = refer(helper.returnType.dartName)
              // The leading blank keeps consecutive helpers from running their
              // comment onto the previous function's last line.
              ..docs.addAll(['', '// ${helper.nodeId}'])
              ..requiredParameters.addAll([
                for (final parameter in helper.parameters)
                  Parameter(
                    (p) => p
                      ..name = parameter.name
                      ..type = refer(parameter.type.dartName),
                  ),
              ])
              ..lambda = helper.isExpressionBody
              ..body = Code(helper.body),
          ),
      ];
}
