import 'package:code_builder/code_builder.dart';
import 'package:lattice_core/lattice_core.dart';

import '../ir/page_ir.dart';
import 'render.dart';

/// Step 3 of the pipeline (§7.5): one [PageIr] becomes one Dart library.
///
/// The shape is fixed on purpose — signals as fields, one method per event
/// chain, a plain `build` — because that is what a Flutter developer would
/// have written by hand, and because those anchors are what a future
/// graph ↔ code round trip would key off (R18).
class PageEmitter {
  const PageEmitter();

  static const _material = 'package:flutter/material.dart';

  String emit(ProjectIr projectIr, PageIr ir) {
    final config = projectIr.project.config;
    final needsRuntime = ir.signals.isNotEmpty || ir.hoisted.isNotEmpty;

    final library = Library(
      (b) => b
        ..directives.addAll([
          Directive.import(_material),
          if (needsRuntime) Directive.import(_runtimeImport(config)),
          if (ir.usesModels) Directive.import('../models.dart'),
        ])
        ..body.addAll([
          if (ir.isStateful) ..._stateful(ir) else _stateless(ir),
          ..._helpers(ir),
        ]),
    );

    return '${_header(ir)}\n${library.accept(newEmitter())}';
  }

  String _runtimeImport(ProjectConfig config) => switch (config.runtime) {
        RuntimeBackend.signals =>
          'package:signals_flutter/signals_flutter.dart',
        RuntimeBackend.valueNotifier =>
          'package:lattice_runtime/lattice_runtime.dart',
      };

  String _header(PageIr ir) => '''
// Generated by Lattice from ${ir.page.id}.
//
// Safe to edit once you have ejected: this is ordinary Flutter code with no
// runtime dependency on the editor. Node ids appear as comments so a change
// here can still be traced back to the graph.
''';

  // ---------------------------------------------------------------------------

  List<Spec> _stateful(PageIr ir) {
    final stateName = '_${ir.className}State';
    return [
      Class(
        (b) => b
          ..name = ir.className
          ..extend = refer('StatefulWidget')
          ..constructors.add(_keyConstructor(ir.className))
          ..methods.add(
            Method(
              (m) => m
                ..name = 'createState'
                ..returns = refer('State<${ir.className}>')
                ..annotations.add(refer('override'))
                ..lambda = true
                ..body = Code('$stateName()'),
            ),
          ),
      ),
      Class(
        (b) => b
          ..name = stateName
          ..extend = refer('State<${ir.className}>')
          ..fields.addAll([
            for (final signal in ir.signals) _signalField(signal),
            for (final hoist in ir.hoisted) _hoistField(hoist),
          ])
          ..methods.addAll([
            for (final handler in ir.handlers) _handlerMethod(handler),
            _buildMethod(ir),
          ]),
      ),
    ];
  }

  Spec _stateless(PageIr ir) => Class(
        (b) => b
          ..name = ir.className
          ..extend = refer('StatelessWidget')
          ..constructors.add(_keyConstructor(ir.className))
          ..methods.add(_buildMethod(ir)),
      );

  Constructor _keyConstructor(String className) => Constructor(
        (c) => c
          ..constant = true
          ..optionalParameters.add(
            Parameter(
              (p) => p
                ..name = 'key'
                ..named = true
                ..toSuper = true,
            ),
          ),
      );

  Field _signalField(SignalIr signal) => Field(
        (f) => f
          ..name = signal.name
          ..modifier = FieldModifier.final$
          ..docs.add('// ${signal.nodeId}')
          ..assignment = Code(
            'signal<${signal.type.dartName}>'
            '(${renderExpression(signal.init.standalone())})',
          ),
      );

  Field _hoistField(HoistedIr hoist) => Field(
        (f) => f
          ..name = hoist.name
          ..late = true
          ..modifier = FieldModifier.final$
          ..docs.add('// ${hoist.pin.nodeId}')
          ..assignment = Code(
            'computed(() => ${renderExpression(hoist.body.bare())})',
          ),
      );

  Method _handlerMethod(HandlerIr handler) => Method(
        (m) => m
          ..name = handler.name
          ..returns = refer('void')
          ..docs.add('// ${handler.trace.join(' -> ')}')
          ..requiredParameters.addAll([
            if (handler.payloadType != null)
              Parameter(
                (p) => p
                  ..name = handler.payloadName
                  ..type = refer(handler.payloadType!.dartName),
              ),
          ])
          ..body = Block.of(handler.statements),
      );

  Method _buildMethod(PageIr ir) => Method(
        (m) => m
          ..name = 'build'
          ..returns = refer('Widget')
          ..annotations.add(refer('override'))
          ..requiredParameters.add(
            Parameter(
              (p) => p
                ..name = 'context'
                ..type = refer('BuildContext'),
            ),
          )
          ..body = Code('return ${renderExpression(ir.body.standalone())};'),
      );

  /// `Computed` and `Dart Code` bodies become top-level private functions:
  /// they are pure by construction, so nothing is gained by hiding them in the
  /// State class, and a reader can see at a glance that they touch no state.
  List<Spec> _helpers(PageIr ir) => [
        for (final helper in ir.helpers)
          Method(
            (m) => m
              ..name = helper.name
              ..returns = refer(helper.returnType.dartName)
              ..docs.add('// ${helper.nodeId}')
              ..requiredParameters.addAll([
                for (final parameter in helper.parameters)
                  Parameter(
                    (p) => p
                      ..name = parameter.name
                      ..type = refer(parameter.type.dartName),
                  ),
              ])
              ..lambda = helper.isExpressionBody
              ..body = Code(helper.body),
          ),
      ];
}
