import 'package:lattice_core/lattice_core.dart';

/// Everything in a generated project that is not Dart: the pubspec, the lint
/// configuration, the README, and the CI matrix that produces the platforms
/// this machine cannot build locally (§7.9, ADR-006).
class SupportFiles {
  const SupportFiles();

  static const signalsVersion = '^7.1.0';

  /// Renders [value] as a quoted YAML scalar.
  ///
  /// An unquoted description containing ": " is not a string — it is a nested
  /// mapping, and `flutter create` fails to parse the pubspec it produced.
  static String _yaml(String value) => "'${value.replaceAll("'", "''")}'";

  /// [runtimePath] is the relative path from the generated project to
  /// `packages/lattice_runtime`, used only by the zero-dependency backend.
  String pubspec(
    Project project, {
    String? runtimePath,
    bool usesHttp = false,
  }) {
    final config = project.config;
    final runtimeDependency = switch (config.runtime) {
      RuntimeBackend.signals => '  signals_flutter: $signalsVersion',
      RuntimeBackend.valueNotifier => runtimePath == null
          ? '  lattice_runtime: ^0.1.0'
          : '  lattice_runtime:\n    path: $runtimePath',
    };

    return '''
# Generated by Lattice. Edit freely after ejecting.
name: ${config.packageName}
description: ${_yaml(config.description)}
publish_to: none
version: ${_yaml(config.version)}

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
$runtimeDependency${usesHttp ? '\n  http: ^1.2.0' : ''}

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
''';
  }

  /// The generated project's lint configuration.
  ///
  /// Platform directories are excluded up front because `flutter analyze` and
  /// `flutter build` will otherwise append them themselves, rewriting a
  /// generated file and making every subsequent build report a phantom change.
  String analysisOptions(Project project) {
    final excluded = [
      'build/**',
      for (final target in project.config.targets)
        '${_platformDirectory(target)}/**',
    ];
    return '''
# Generated by Lattice.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
${excluded.map((e) => '    - $e').join('\n')}

linter:
  rules:
    # Lattice decides const-ness structurally: a widget is emitted `const`
    # exactly when none of its arguments read a signal (§8). These two rules
    # would second-guess that decision without knowing about the graph, so they
    # are off rather than being worked around with ignore comments.
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
''';
  }

  static String _platformDirectory(BuildTarget target) => target.id;

  String readme(Project project) {
    final config = project.config;
    return '''
# ${config.appName}

Generated by [Lattice](https://github.com/) from a node graph. This is a normal
Flutter project: there is no runtime dependency on the editor and nothing here
needs Lattice to build.

## Run it

```bash
flutter pub get
flutter run
```

## What is generated, and what is yours

| Path | Regenerated | Notes |
|---|---|---|
| `lib/main.dart` | yes | route table and `MaterialApp` |
| `lib/pages/` | yes | one file per page |
| `lib/models.dart` | yes | one class per struct |
| `lib/custom/` | **no** | your own Dart; call it from a `Dart Code` node |

Editing a regenerated file is fine — it is ordinary Dart — but the next build
from the editor will overwrite it. To leave Lattice for good, run
`lattice export` and delete the `.lattice/` directory.

## Building for other platforms

`flutter build <target>` works as usual. Desktop targets can only be built on
their own operating system, so `.github/workflows/build.yml` covers the ones
this machine cannot: push the repository and the matrix produces Linux, Windows
and macOS artefacts.

Version ${config.version} · bundle id `${config.bundleId}`
''';
  }

  String customReadme() => '''
# Hand-written Dart

Nothing in this directory is ever overwritten by code generation (§7.8).

Put helper functions here and call them from a `Dart Code` node in the graph.
That is what keeps Lattice's expressive ceiling equal to Dart's own: anything
the node library cannot say, you can write here and wire in.
''';

  /// The GitHub Actions matrix (§7.9). One repository plus one push gets every
  /// desktop target, which is the answer to "I only have Linux but need a
  /// Windows installer".
  String ciWorkflow(Project project) {
    final config = project.config;
    final targets = config.targets.map((t) => t.id).toSet();
    final jobs = <String>[];

    // The server is part of the artefact set: a full-stack project that ships
    // only its client is half a release (§7.7).
    if (project.hasServer) {
      jobs.add('''
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
        working-directory: server
      - run: dart analyze
        working-directory: server
      - name: Compile a single self-contained binary
        run: dart compile exe bin/server.dart -o ${config.packageName}_server
        working-directory: server
      - uses: actions/upload-artifact@v4
        with:
          name: ${config.packageName}-server
          path: server/${config.packageName}_server''');
    }

    if (targets.contains('linux')) {
      jobs.add('''
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: sudo apt-get update && sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter pub get
      - run: flutter build linux --release
      - uses: actions/upload-artifact@v4
        with:
          name: ${config.packageName}-linux
          path: build/linux/x64/release/bundle''');
    }
    if (targets.contains('windows')) {
      jobs.add('''
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: flutter pub get
      - run: flutter build windows --release
      - uses: actions/upload-artifact@v4
        with:
          name: ${config.packageName}-windows
          path: build/windows/x64/runner/Release''');
    }
    if (targets.contains('macos')) {
      jobs.add('''
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: flutter pub get
      - run: flutter build macos --release
      - uses: actions/upload-artifact@v4
        with:
          name: ${config.packageName}-macos
          path: build/macos/Build/Products/Release''');
    }
    if (targets.contains('android')) {
      jobs.add('''
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: flutter pub get
      # Unsigned by design: signing is a wizard in the Build panel, and
      # credentials never enter the project files (§7.9).
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: ${config.packageName}-android
          path: build/app/outputs/flutter-apk/app-release.apk''');
    }
    if (targets.contains('web')) {
      jobs.add('''
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: flutter pub get
      - run: flutter build web --release
      - uses: actions/upload-artifact@v4
        with:
          name: ${config.packageName}-web
          path: build/web''');
    }

    return '''
# Generated by Lattice.
#
# Flutter can only build a desktop target on its own operating system, so the
# full set of platforms comes from this matrix rather than from any one
# machine (ADR-006).
name: build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
${jobs.join('\n\n')}
''';
  }

  /// The release matrix (R22): on a version tag, every target produces a
  /// *distributable* rather than a build directory, and they all land on one
  /// GitHub Release.
  ///
  /// Separate from `build.yml` on purpose. That one answers "does main still
  /// compile everywhere" and should stay fast; this one is slow, signs things,
  /// and should only run when a release is actually being cut.
  String releaseWorkflow(Project project) {
    final config = project.config;
    final targets = config.targets.map((t) => t.id).toSet();
    final jobs = <String>[];

    // Credentials come from repository secrets and are handed to the build as
    // environment variables. They never enter the project files (§7.9), which
    // is why the generated project can be public.
    const androidEnv = '''
        env:
          LATTICE_ANDROID_KEYSTORE: \${{ github.workspace }}/upload.jks
          LATTICE_ANDROID_KEY_ALIAS: \${{ secrets.ANDROID_KEY_ALIAS }}
          LATTICE_ANDROID_STORE_PASSWORD: \${{ secrets.ANDROID_STORE_PASSWORD }}
          LATTICE_ANDROID_KEY_PASSWORD: \${{ secrets.ANDROID_KEY_PASSWORD }}''';

    String job(
      String name,
      String runner, {
      String setup = '',
      String env = '',
    }) =>
        '''
  $name:
    runs-on: $runner
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: dart pub global activate flutter_distributor
$setup      - name: Package
        run: \$HOME/.pub-cache/bin/flutter_distributor package --platform $name --targets \${{ env.TARGETS }}
$env
      - uses: actions/upload-artifact@v4
        with:
          name: ${config.packageName}-$name
          path: dist/**/*''';

    if (targets.contains('linux')) {
      jobs.add(job(
        'linux',
        'ubuntu-latest',
        setup:
            '''      - run: sudo apt-get update && sudo apt-get install -y ninja-build libgtk-3-dev fuse
      - name: appimagetool
        run: |
          curl -L -o /usr/local/bin/appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x /usr/local/bin/appimagetool
''',
      ).replaceAll(r'${{ env.TARGETS }}', 'appimage,deb'));
    }
    if (targets.contains('windows')) {
      jobs.add(job('windows', 'windows-latest')
          .replaceAll(r'${{ env.TARGETS }}', 'exe,msix')
          .replaceAll(r'$HOME/.pub-cache/bin/', ''));
    }
    if (targets.contains('macos')) {
      jobs.add(job('macos', 'macos-latest')
          .replaceAll(r'${{ env.TARGETS }}', 'dmg'));
    }
    if (targets.contains('android')) {
      jobs.add(job(
        'android',
        'ubuntu-latest',
        setup: '''      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - name: Restore the upload keystore
        # Base64 in a secret, decoded to a file the build can read and the
        # repository never sees.
        run: echo "\${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > upload.jks
''',
        env: androidEnv,
      ).replaceAll(r'${{ env.TARGETS }}', 'apk,aab'));
    }
    if (targets.contains('web')) {
      jobs.add(
          job('web', 'ubuntu-latest').replaceAll(r'${{ env.TARGETS }}', 'zip'));
    }

    return '''
# Generated by Lattice.
#
# Cutting a release:
#
#     git tag v${config.semver} && git push --tags
#
# Signing credentials come from repository secrets, never from these files
# (§7.9). Which secrets each platform wants is listed in the Build panel's
# signing wizard, and in docs/signing.md of the Lattice repository.
name: release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
${jobs.join('\n\n')}

  publish:
    needs: [${targets.where((t) => t != 'ios').join(', ')}]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with: { path: artifacts }
      - uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          fail_on_unmatched_files: true
''';
  }

  /// `flutter_distributor`'s configuration — one file covering every format
  /// the project targets, so the user never has to learn appimagetool, msix,
  /// dmgbuild or bundletool separately (§7.9 step 4).
  String distributeOptions(Project project) {
    final config = project.config;
    const formats = {
      'linux': ['appimage', 'deb'],
      'windows': ['exe', 'msix'],
      'macos': ['dmg'],
      'android': ['apk', 'aab'],
      'ios': ['ipa'],
      'web': ['zip'],
    };

    final jobs = <String>[];
    for (final target in config.targets) {
      for (final format in formats[target.id] ?? const <String>[]) {
        jobs.add('''
      - name: release-${target.id}-$format
        package:
          platform: ${target.id}
          target: $format''');
      }
    }

    return '''
# Generated by Lattice.
#
#   dart pub global activate flutter_distributor
#   flutter_distributor release --name release
output: dist/
releases:
  - name: release
    jobs:
${jobs.join('\n')}

variables:
  APP_NAME: ${config.appName}
  APP_VERSION: ${config.semver}
  APP_ID: ${config.bundleId}
''';
  }

  String gitignore() => '''
# Generated by Lattice.
.dart_tool/
build/
.flutter-plugins
.flutter-plugins-dependencies
pubspec.lock
''';
}
