import 'package:lattice_core/lattice_core.dart';

/// Everything in a generated project that is not Dart: the pubspec, the lint
/// configuration, the README, and the CI matrix that produces the platforms
/// this machine cannot build locally (§7.9, ADR-006).
class SupportFiles {
  const SupportFiles();

  static const signalsVersion = '^7.1.0';

  /// Renders [value] as a quoted YAML scalar.
  ///
  /// An unquoted description containing ": " is not a string — it is a nested
  /// mapping, and `flutter create` fails to parse the pubspec it produced.
  static String _yaml(String value) => "'${value.replaceAll("'", "''")}'";

  /// [runtimePath] is the relative path from the generated project to
  /// `packages/lattice_runtime`, used only by the zero-dependency backend.
  String pubspec(
    Project project, {
    String? runtimePath,
    bool usesHttp = false,
  }) {
    final config = project.config;
    final runtimeDependency = switch (config.runtime) {
      RuntimeBackend.signals => '  signals_flutter: $signalsVersion',
      RuntimeBackend.valueNotifier => runtimePath == null
          ? '  lattice_runtime: ^0.1.0'
          : '  lattice_runtime:\n    path: $runtimePath',
    };

    return '''
# Generated by Lattice. Edit freely after ejecting.
name: ${config.packageName}
description: ${_yaml(config.description)}
publish_to: none
version: ${_yaml(config.version)}

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
$runtimeDependency${usesHttp ? '\n  http: ^1.2.0' : ''}

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
''';
  }

  /// The generated project's lint configuration.
  ///
  /// Platform directories are excluded up front because `flutter analyze` and
  /// `flutter build` will otherwise append them themselves, rewriting a
  /// generated file and making every subsequent build report a phantom change.
  String analysisOptions(Project project) {
    final excluded = [
      'build/**',
      for (final target in project.config.targets)
        '${_platformDirectory(target)}/**',
    ];
    return '''
# Generated by Lattice.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
${excluded.map((e) => '    - $e').join('\n')}

linter:
  rules:
    # Lattice decides const-ness structurally: a widget is emitted `const`
    # exactly when none of its arguments read a signal (§8). These two rules
    # would second-guess that decision without knowing about the graph, so they
    # are off rather than being worked around with ignore comments.
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
''';
  }

  static String _platformDirectory(BuildTarget target) => target.id;

  String readme(Project project) {
    final config = project.config;
    return '''
# ${config.appName}

Generated by [Lattice](https://github.com/) from a node graph. This is a normal
Flutter project: there is no runtime dependency on the editor and nothing here
needs Lattice to build.

## Run it

```bash
flutter pub get
flutter run
```

## What is generated, and what is yours

| Path | Regenerated | Notes |
|---|---|---|
| `lib/main.dart` | yes | route table and `MaterialApp` |
| `lib/pages/` | yes | one file per page |
| `lib/models.dart` | yes | one class per struct |
| `lib/custom/` | **no** | your own Dart; call it from a `Dart Code` node |

Editing a regenerated file is fine — it is ordinary Dart — but the next build
from the editor will overwrite it. To leave Lattice for good, run
`lattice export` and delete the `.lattice/` directory.

## Building for other platforms

`flutter build <target>` works as usual. Desktop targets can only be built on
their own operating system, so `.github/workflows/build.yml` covers the ones
this machine cannot: push the repository and the matrix produces Linux, Windows
and macOS artefacts.

Version ${config.version} · bundle id `${config.bundleId}`
''';
  }

  String customReadme() => '''
# Hand-written Dart

Nothing in this directory is ever overwritten by code generation (§7.8).

Put helper functions here and call them from a `Dart Code` node in the graph.
That is what keeps Lattice's expressive ceiling equal to Dart's own: anything
the node library cannot say, you can write here and wire in.
''';

  /// The GitHub Actions matrix (§7.9). One repository plus one push gets every
  /// desktop target, which is the answer to "I only have Linux but need a
  /// Windows installer".
  String ciWorkflow(Project project) {
    final config = project.config;
    final targets = config.targets.map((t) => t.id).toSet();
    final jobs = <String>[];

    if (targets.contains('linux')) {
      jobs.add('''
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: sudo apt-get update && sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter pub get
      - run: flutter build linux --release
      - uses: actions/upload-artifact@v4
        with:
          name: ${config.packageName}-linux
          path: build/linux/x64/release/bundle''');
    }
    if (targets.contains('windows')) {
      jobs.add('''
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: flutter pub get
      - run: flutter build windows --release
      - uses: actions/upload-artifact@v4
        with:
          name: ${config.packageName}-windows
          path: build/windows/x64/runner/Release''');
    }
    if (targets.contains('macos')) {
      jobs.add('''
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: flutter pub get
      - run: flutter build macos --release
      - uses: actions/upload-artifact@v4
        with:
          name: ${config.packageName}-macos
          path: build/macos/Build/Products/Release''');
    }
    if (targets.contains('android')) {
      jobs.add('''
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: flutter pub get
      # Unsigned by design: signing is a wizard in the Build panel, and
      # credentials never enter the project files (§7.9).
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: ${config.packageName}-android
          path: build/app/outputs/flutter-apk/app-release.apk''');
    }
    if (targets.contains('web')) {
      jobs.add('''
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: flutter pub get
      - run: flutter build web --release
      - uses: actions/upload-artifact@v4
        with:
          name: ${config.packageName}-web
          path: build/web''');
    }

    return '''
# Generated by Lattice.
#
# Flutter can only build a desktop target on its own operating system, so the
# full set of platforms comes from this matrix rather than from any one
# machine (ADR-006).
name: build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
${jobs.join('\n\n')}
''';
  }

  /// `flutter_distributor`'s configuration — one file covering every format
  /// the project targets, so the user never has to learn appimagetool, msix,
  /// dmgbuild or bundletool separately (§7.9 step 4).
  String distributeOptions(Project project) {
    final config = project.config;
    const formats = {
      'linux': ['appimage', 'deb'],
      'windows': ['exe', 'msix'],
      'macos': ['dmg'],
      'android': ['apk', 'aab'],
      'ios': ['ipa'],
      'web': ['zip'],
    };

    final jobs = <String>[];
    for (final target in config.targets) {
      for (final format in formats[target.id] ?? const <String>[]) {
        jobs.add('''
      - name: release-${target.id}-$format
        package:
          platform: ${target.id}
          target: $format''');
      }
    }

    return '''
# Generated by Lattice.
#
#   dart pub global activate flutter_distributor
#   flutter_distributor release --name release
output: dist/
releases:
  - name: release
    jobs:
${jobs.join('\n')}

variables:
  APP_NAME: ${config.appName}
  APP_VERSION: ${config.semver}
  APP_ID: ${config.bundleId}
''';
  }

  String gitignore() => '''
# Generated by Lattice.
.dart_tool/
build/
.flutter-plugins
.flutter-plugins-dependencies
pubspec.lock
''';
}
