import 'package:collection/collection.dart';

import 'data_model.dart';
import 'json_utils.dart';
import 'page.dart';

/// Which reactive primitives the generated code is built on.
///
/// §15 leaves the default open until the end of M0, so the choice is a project
/// setting and `lattice_runtime` presents one façade over both.
enum RuntimeBackend {
  /// `signals_flutter` — maps one-to-one onto the graph model (§7.5).
  signals('signals'),

  /// `ValueNotifier` + `ValueListenableBuilder` — zero extra dependencies.
  valueNotifier('value_notifier');

  const RuntimeBackend(this.id);

  final String id;

  static RuntimeBackend fromId(String? id) =>
      values.firstWhereOrNull((b) => b.id == id) ?? RuntimeBackend.signals;
}

/// Build targets Lattice knows how to configure and package (§7.9).
enum BuildTarget {
  linux('linux'),
  windows('windows'),
  macos('macos'),
  android('android'),
  ios('ios'),
  web('web');

  const BuildTarget(this.id);

  final String id;

  static BuildTarget? fromId(String id) =>
      values.firstWhereOrNull((t) => t.id == id);

  /// Host operating systems that can build this target locally. Everything
  /// else has to go through the generated CI matrix (ADR-006).
  Set<String> get buildableOn => switch (this) {
        BuildTarget.linux => {'linux'},
        BuildTarget.windows => {'windows'},
        BuildTarget.macos || BuildTarget.ios => {'macos'},
        BuildTarget.android || BuildTarget.web => {'linux', 'macos', 'windows'},
      };
}

/// Everything the build pipeline needs that isn't part of the graph (§7.9).
final class ProjectConfig {
  const ProjectConfig({
    required this.appName,
    required this.packageName,
    this.bundleId = 'com.example.app',
    this.version = '1.0.0+1',
    this.description = 'Generated by Lattice.',
    this.organization = 'com.example',
    this.runtime = RuntimeBackend.signals,
    this.targets = const [BuildTarget.linux, BuildTarget.web],
  });

  /// Human-facing application name (window title, launcher label).
  final String appName;

  /// Dart package name of the generated project; must be a valid identifier.
  final String packageName;

  final String bundleId;
  final String version;
  final String description;
  final String organization;
  final RuntimeBackend runtime;
  final List<BuildTarget> targets;

  factory ProjectConfig.fromJson(Map<String, Object?> json, String path) {
    final rawTargets = json.arrOrEmpty('targets', path);
    final targets = <BuildTarget>[
      for (final t in rawTargets)
        if (t is String && BuildTarget.fromId(t) != null)
          BuildTarget.fromId(t)!,
    ];
    return ProjectConfig(
      appName: json.strOr('appName', 'Lattice App'),
      packageName: json.strOr('packageName', 'lattice_app'),
      bundleId: json.strOr('bundleId', 'com.example.app'),
      version: json.strOr('version', '1.0.0+1'),
      description: json.strOr('description', 'Generated by Lattice.'),
      organization: json.strOr('organization', 'com.example'),
      runtime: RuntimeBackend.fromId(json['runtime'] as String?),
      targets: targets.isEmpty
          ? const [BuildTarget.linux, BuildTarget.web]
          : targets,
    );
  }

  Map<String, Object?> toJson() => {
        'appName': appName,
        'bundleId': bundleId,
        'description': description,
        'organization': organization,
        'packageName': packageName,
        'runtime': runtime.id,
        'targets': [for (final t in targets) t.id],
        'version': version,
      };

  /// The semver part of [version], without the `+build` suffix.
  String get semver => version.split('+').first;

  ProjectConfig copyWith({
    String? appName,
    String? packageName,
    String? bundleId,
    String? version,
    String? description,
    String? organization,
    RuntimeBackend? runtime,
    List<BuildTarget>? targets,
  }) =>
      ProjectConfig(
        appName: appName ?? this.appName,
        packageName: packageName ?? this.packageName,
        bundleId: bundleId ?? this.bundleId,
        version: version ?? this.version,
        description: description ?? this.description,
        organization: organization ?? this.organization,
        runtime: runtime ?? this.runtime,
        targets: targets ?? this.targets,
      );

  @override
  bool operator ==(Object other) =>
      other is ProjectConfig &&
      other.appName == appName &&
      other.packageName == packageName &&
      other.bundleId == bundleId &&
      other.version == version &&
      other.description == description &&
      other.organization == organization &&
      other.runtime == runtime &&
      const ListEquality<BuildTarget>().equals(other.targets, targets);

  @override
  int get hashCode =>
      Object.hash(appName, packageName, bundleId, version, runtime);
}

/// An entire Lattice project (§5).
final class Project {
  Project({
    required this.id,
    required this.config,
    List<Page>? pages,
    List<DataModelDef>? models,
  })  : pages = List.unmodifiable(pages ?? const []),
        models = List.unmodifiable(models ?? const []);

  final String id;
  final ProjectConfig config;
  final List<Page> pages;
  final List<DataModelDef> models;

  /// Reads the `project.json` manifest. [pages] and [models] live in their own
  /// files (§7.4) and are supplied by the loader.
  factory Project.fromManifest(
    Map<String, Object?> json, {
    List<Page> pages = const [],
    List<DataModelDef> models = const [],
    String path = 'project',
  }) =>
      Project(
        id: json.strOr('id', 'project'),
        config: ProjectConfig.fromJson(
          json.objOrNull('config', path) ?? const {},
          '$path.config',
        ),
        pages: pages,
        models: models,
      );

  Map<String, Object?> toManifestJson() => {
        'config': config.toJson(),
        'id': id,
        'pages': [for (final p in pages) p.id],
      };

  Page? page(String id) => pages.firstWhereOrNull((p) => p.id == id);

  DataModelDef? model(String name) =>
      models.firstWhereOrNull((m) => m.name == name);

  /// The page the app routes to first: the one flagged `isHome`, else the
  /// first declared.
  Page? get homePage =>
      pages.firstWhereOrNull((p) => p.isHome) ?? pages.firstOrNull;

  Project copyWith({
    ProjectConfig? config,
    List<Page>? pages,
    List<DataModelDef>? models,
  }) =>
      Project(
        id: id,
        config: config ?? this.config,
        pages: pages ?? this.pages,
        models: models ?? this.models,
      );

  /// Replaces one page in place, keeping declaration order.
  Project withPage(Page page) => copyWith(
        pages: [
          for (final p in pages)
            if (p.id == page.id) page else p,
        ],
      );

  @override
  bool operator ==(Object other) =>
      other is Project &&
      other.id == id &&
      other.config == config &&
      const ListEquality<Page>().equals(other.pages, pages) &&
      const ListEquality<DataModelDef>().equals(other.models, models);

  @override
  int get hashCode => Object.hash(id, config, pages.length, models.length);
}
